import{a as d,S as m,i as c}from"./assets/vendor-B5nsgUv9.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))o(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&o(n)}).observe(document,{childList:!0,subtree:!0});function s(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function o(e){if(e.ep)return;e.ep=!0;const t=s(e);fetch(e.href,t)}})();const y=void 0,g="https://pixabay.com/api/";d.create({baseURL:g,params:{key:y,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15}});function h(i){return Promise.reject(new Error("Pixabay API key is missing. Set VITE_PIXABAY_KEY in your .env file."))}const l=document.querySelector(".gallery"),a=document.querySelector(".loader"),v=new m(".gallery a",{captionsData:"alt",captionDelay:250});function b(i){if(!l)return;const r=i.map(({webformatURL:s,largeImageURL:o,tags:e,likes:t,views:n,comments:f,downloads:p})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${o}">
          <img class="gallery-image" src="${s}" alt="${e}" loading="lazy" />
          <div class="info">
            <p class="info-label">Likes<span class="info-value">${t}</span></p>
            <p class="info-label">Views<span class="info-value">${n}</span></p>
            <p class="info-label">Comments<span class="info-value">${f}</span></p>
            <p class="info-label">Downloads<span class="info-value">${p}</span></p>
          </div>
        </a>
      </li>`).join("");l.insertAdjacentHTML("beforeend",r),v.refresh()}function L(){l&&(l.innerHTML="")}function P(){a==null||a.classList.remove("is-hidden")}function A(){a==null||a.classList.add("is-hidden")}const u=document.querySelector(".form"),I=document.querySelector('input[name="search-text"]');u.addEventListener("submit",i=>{if(i.preventDefault(),!I.value.trim()){c.warning({message:"Please enter a search query.",position:"topRight"});return}L(),P(),h().then(({hits:s})=>{if(!s.length){c.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"#f35c5c",progressBarColor:"#fff"});return}b(s)}).catch(s=>{c.error({message:(s==null?void 0:s.message)==="Pixabay API key is missing. Set VITE_PIXABAY_KEY in your .env file."?"API key is missing. Add VITE_PIXABAY_KEY to .env and restart the dev server.":"Failed to load images.",position:"topRight"})}).finally(()=>{A(),u.reset()})});
//# sourceMappingURL=index.js.map
