import{a as y,S as h,i as l}from"./assets/vendor-B5nsgUv9.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function o(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=o(e);fetch(e.href,t)}})();const p="54645624-93bc72701cdff138f1edf2876",b="https://pixabay.com/api/",L=y.create({baseURL:b,params:{key:p,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15}}),d=!!p;function v(r){return L.get("",{params:{q:r}}).then(({data:s})=>s)}const c=document.querySelector(".gallery"),a=document.querySelector(".loader"),P=new h(".gallery a",{captionsData:"alt",captionDelay:250});function q(r){if(!c)return;const s=r.map(({webformatURL:o,largeImageURL:i,tags:e,likes:t,views:n,comments:m,downloads:g})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${i}">
          <img class="gallery-image" src="${o}" alt="${e}" loading="lazy" />
          <div class="info">
            <p class="info-label">Likes<span class="info-value">${t}</span></p>
            <p class="info-label">Views<span class="info-value">${n}</span></p>
            <p class="info-label">Comments<span class="info-value">${m}</span></p>
            <p class="info-label">Downloads<span class="info-value">${g}</span></p>
          </div>
        </a>
      </li>`).join("");c.insertAdjacentHTML("beforeend",s),P.refresh()}function A(){c&&(c.innerHTML="")}function S(){a==null||a.classList.remove("is-hidden")}function I(){a==null||a.classList.add("is-hidden")}const u=document.querySelector(".form"),x=document.querySelector('input[name="search-text"]'),f=u.querySelector('button[type="submit"]');d||(l.error({message:"API key отсутствует в коде приложения.",position:"topRight",backgroundColor:"#f35c5c",progressBarColor:"#fff"}),f.disabled=!0,f.textContent="Add API key");u.addEventListener("submit",r=>{if(r.preventDefault(),!d)return;const s=x.value.trim();if(!s){l.warning({message:"Please enter a search query.",position:"topRight"});return}A(),S(),v(s).then(({hits:o})=>{if(!o.length){l.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"#f35c5c",progressBarColor:"#fff"});return}q(o)}).catch(o=>{l.error({message:(o==null?void 0:o.message)==="Pixabay API key is missing in the app code."?"API key отсутствует в коде приложения.":"Failed to load images.",position:"topRight"})}).finally(()=>{I(),u.reset()})});
//# sourceMappingURL=index.js.map
