import{a as y,S as h,i as l}from"./assets/vendor-B5nsgUv9.js";(function(){const s=document.createElement("link").relList;if(s&&s.supports&&s.supports("modulepreload"))return;for(const e of document.querySelectorAll('link[rel="modulepreload"]'))i(e);new MutationObserver(e=>{for(const t of e)if(t.type==="childList")for(const n of t.addedNodes)n.tagName==="LINK"&&n.rel==="modulepreload"&&i(n)}).observe(document,{childList:!0,subtree:!0});function r(e){const t={};return e.integrity&&(t.integrity=e.integrity),e.referrerPolicy&&(t.referrerPolicy=e.referrerPolicy),e.crossOrigin==="use-credentials"?t.credentials="include":e.crossOrigin==="anonymous"?t.credentials="omit":t.credentials="same-origin",t}function i(e){if(e.ep)return;e.ep=!0;const t=r(e);fetch(e.href,t)}})();const p="54645624-93bc72701cdff138f1edf2876",b="https://pixabay.com/api/",v=y.create({baseURL:b,params:{key:p,image_type:"photo",orientation:"horizontal",safesearch:!0,per_page:15}}),d=!!p;function A(o){return v.get("",{params:{q:o}}).then(({data:s})=>s)}const c=document.querySelector(".gallery"),a=document.querySelector(".loader"),L=new h(".gallery a",{captionsData:"alt",captionDelay:250});function P(o){if(!c)return;const s=o.map(({webformatURL:r,largeImageURL:i,tags:e,likes:t,views:n,comments:m,downloads:g})=>`
      <li class="gallery-item">
        <a class="gallery-link" href="${i}">
          <img class="gallery-image" src="${r}" alt="${e}" loading="lazy" />
          <div class="info">
            <p class="info-label">Likes<span class="info-value">${t}</span></p>
            <p class="info-label">Views<span class="info-value">${n}</span></p>
            <p class="info-label">Comments<span class="info-value">${m}</span></p>
            <p class="info-label">Downloads<span class="info-value">${g}</span></p>
          </div>
        </a>
      </li>`).join("");c.insertAdjacentHTML("beforeend",s),L.refresh()}function I(){c&&(c.innerHTML="")}function S(){a==null||a.classList.remove("is-hidden")}function q(){a==null||a.classList.add("is-hidden")}const u=document.querySelector(".form"),E=document.querySelector('input[name="search-text"]'),f=u.querySelector('button[type="submit"]');d||(l.error({message:"API key is missing. Add VITE_PIXABAY_KEY to .env and restart the dev server.",position:"topRight",backgroundColor:"#f35c5c",progressBarColor:"#fff"}),f.disabled=!0,f.textContent="Add API key");u.addEventListener("submit",o=>{if(o.preventDefault(),!d)return;const s=E.value.trim();if(!s){l.warning({message:"Please enter a search query.",position:"topRight"});return}I(),S(),A(s).then(({hits:r})=>{if(!r.length){l.error({message:"Sorry, there are no images matching your search query. Please try again!",position:"topRight",backgroundColor:"#f35c5c",progressBarColor:"#fff"});return}P(r)}).catch(r=>{l.error({message:(r==null?void 0:r.message)==="Pixabay API key is missing. Set VITE_PIXABAY_KEY in your .env file."?"API key is missing. Add VITE_PIXABAY_KEY to .env and restart the dev server.":"Failed to load images.",position:"topRight"})}).finally(()=>{q(),u.reset()})});
//# sourceMappingURL=index.js.map
